INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (1, 'Bio stuff', 'Biology I', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (2, 'Bio stuff', 'Biology II', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (3, 'anatomy stuff', 'Anatomy', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (4, 'bio stuff', 'Microbiology', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (5, 'Bio stuff', 'Genetics', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (6, 'Bio stuff', 'Physiology', 'Biology');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (7, 'PreCal stuff', 'Pre-Calculus', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (8, 'Calc stuff', 'Calculus I', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (9, 'Calc stuff', 'Calculus II', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (10, 'Calc stuff', 'Calculus III', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (11, 'Statistics stuff', 'Statistics', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (12, 'Linear Algebra stuff', 'Linear Algebra', 'Math');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (13, 'Physics stuff', 'Physics I', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (14, 'Physics stuff', 'Physics II', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (15, 'Quantum Mechanics stuff', 'Quantum Mechanics', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (16, 'Astrophysics stuff', 'Astrophysics', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (17, 'Optics', 'Optics stuff', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (18, 'Nuclear  stuff', 'Nuclear Physics', 'Physics');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (19, 'Ochem stuff', 'Organic Chemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (20, 'Gen chem', 'General Chemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (21, 'Anal stuff', 'Analytical Chemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (22, 'Bio chem stuff', 'Biochemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (23, 'Env chem stuff', 'Environmental Chemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (24, 'Phys Chem stuff', 'Physical Chemistry', 'Chemistry');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (25, 'Geo stuff', 'Geology', 'Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (26, 'Star stuff', 'Astronomy', 'Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (27, 'Brain Stuff', 'Neuroscience', 'Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (28, 'Outside stuff', 'Environmental Science', 'Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (29, 'Drawing stuff', 'Drawing', 'Fine Arts');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (30, 'Painting stuff', 'Painting', 'Fine Arts');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (31, 'Sculpture Stuff', 'Sculpture', 'Fine Arts');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (32, 'Photo stuff', 'Photography', 'Fine Arts');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (33, 'Art stuff', 'Art History', 'Fine Arts');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (34, 'Learn Spanish', 'Spanish', 'Language');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (35, 'Learn French', 'French', 'Language');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (36, 'Learn German', 'German', 'Language');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (37, 'Learn Chinese', 'Chinese', 'Language');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (38, 'Literature stuff', 'English Literature', 'Literature');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (39, 'Literature stuff', 'World Literature', 'Literature');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (40, 'Literature stuff', 'American Literature', 'Literature');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (41, 'Literature stuff', 'Comparative Literature', 'Literature');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (42, 'Intro CS stuff', 'Introduction to Computer Science', 'Computer Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (43, 'Data structures stuff', 'Data Structures and Algorithms', 'Computer Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (44, 'Database stuff', 'Database Systems', 'Computer Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (45, 'OS stuff', 'Operating Systems', 'Computer Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (46, 'Intro stuff', 'Introduction to Engineering', 'Engineering');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (47, 'Mech stuff', 'Mechanical Engineering', 'Engineering');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (48, 'Elec stuff', 'Electrical Engineering', 'Engineering');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (49, 'Civil stuff', 'Civil Engineering', 'Engineering');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (50, 'Intro Bus topics', 'Introduction to Business', 'Business');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (51, 'Ads ', 'Marketing', 'Business');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (52, 'Money stuff', 'Finance', 'Business');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (53, 'Mngmt stuff', 'Management', 'Business');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (54, 'Intro Poli sci stuff', 'Introduction to Political Science', 'Political Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (55, 'Poltics', 'Comparative Politics', 'Political Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (56, 'World politics', 'International Relations', 'Political Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (57, 'World policies', 'Public Policy', 'Political Science');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (58, 'Intro Ed topics', 'Introduction to Education', 'Education');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (59, 'Psychology topics', 'Educational Psychology', 'Education');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (60, 'Ed. stuff', 'Curriculum and Instruction', 'Education');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (61, 'Special Ed. Topics', 'Special Education', 'Education');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (62, 'Sociology stuff', 'Sociology', 'Social Sciences');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (63, 'Anthropology stuff', 'Anthropology', 'Social Sciences');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (64, 'Psychcology stuff', 'Psychology', 'Social Sciences');
INSERT INTO studybuddy.courses (course_id, c_description, c_name, subject_area) VALUES (65, 'Econ stuff', 'Economics', 'Social Sciences');
