server:
  port : 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/studybuddy
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: studybuddyofficialsite@gmail.com
    password: ujyv gklb jkem dbjs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true